version: 2
jobs:
  build:
    working_directory: ~/test-ci-code
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: install cypress dependencies
          command: 'sudo apt-get install xvfb libgtk-3-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2'
      - run:
          name: install
          command: 'npm install'
      - run:
          name: test:e2e
          command: 'npm run test:e2e:ci'
